### ISSUE TITLE
Could find no file with path 'results/07_02\render\%05d.jpg'

### ISSUE THREAD

**Issue by 1702609** [isantesteban/vto-learning-based-animation#1]
Hi,

I am trying to render the mesh using the command provided in the documentation. I seem to be running into problems. The error that I am getting is:

[image2 @ 0000020462f9be40] Could find no file with path 'results/07_02\render\%05d.jpg' and index in the range 0-4
results/07_02\render\%05d.jpg: No such file or directory

unknown argument, loading as file: --path
Error: Cannot read file 'F:\vto-learning-based-animation\--path': No such file or directory
Blender quit

Any suggestions on how I can fix this?

**Comment by 1702609** [comment]
I see various files inside 07_02. 

![image](https://user-images.githubusercontent.com/33097868/163976501-ee4fcf29-9890-4bff-af28-d18934306b36.png)

**Comment by isantesteban** [comment]
Could you copy the command that you are using to render the meshes?

**Comment by 1702609** [comment]
I used the exact same command from the documentation:

blender --background rendering/scene.blend --python rendering/render.py --path results/07_02

**Comment by isantesteban** [comment]
Then I don't know what is the problem, sorry

**Comment by marccomino** [comment]
Hello @1702609,

Are you using Windows? I believe the command is supposed to run on linux.

**Comment by 1702609** [comment]
I am running this on Windows, I can run it Linux and will let you know if it works.

**Comment by marccomino** [comment]
I mean, I believe it should work on Windows too, but you need to make sure that the paths are correctly formatted. Maybe changing "/" by "\" does the trick?

**Comment by 1702609** [comment]
It was able to render the meshes on linux but the --path arguement was not recognised. 

![image](https://user-images.githubusercontent.com/33097868/163996536-9fcdbce1-00c1-4700-b6c1-fc4d56f43942.png)

**Comment by 1702609** [comment]
I just took a look at the results folder, and it generated a video successfully. I think it works well in Linux.
